/**
 * Ulaanbaatar corridor graph.
 *
 * Node coordinates are demo-grade (placed by hand from public geography, +/- a few
 * hundred metres). Route shapes are generated by walking this graph. Nothing here is
 * real UB service data - see the DEMO badge and the Settings provenance panel.
 *
 * Place names that appear in the source material are used verbatim so the demo
 * echoes the deck: Peace Ave, Bayankhoshuu Rd, Bayangol, 5th khoroo (S5, S9).
 */

export interface Node {
  id: string;
  name_en: string;
  name_mn: string;
  lon: number;
  lat: number;
  /** 0 = outer, 1 = mid, 2 = central. Drives demand weight and congestion. */
  centrality: 0 | 1 | 2;
  district: string;
}

export const NODES: Node[] = [
  // --- central spine: Peace Avenue, west to east
  { id: 'n-tolgoit', name_en: 'Tolgoit', name_mn: 'Толгойт', lon: 106.7930, lat: 47.9205, centrality: 0, district: 'Songino Khairkhan' },
  { id: 'n-tsaiz', name_en: 'Tsaiz Market', name_mn: 'Цайз зах', lon: 106.8215, lat: 47.9264, centrality: 1, district: 'Songino Khairkhan' },
  { id: 'n-dragon', name_en: 'Dragon Terminal', name_mn: 'Драгон төв', lon: 106.8368, lat: 47.9183, centrality: 1, district: 'Songino Khairkhan' },
  { id: 'n-bayangol', name_en: 'Bayangol', name_mn: 'Баянгол', lon: 106.8572, lat: 47.9161, centrality: 1, district: 'Bayangol' },
  { id: 'n-3r4r', name_en: '3rd & 4th Khoroolol', name_mn: '3, 4-р хороолол', lon: 106.8788, lat: 47.9149, centrality: 2, district: 'Bayangol' },
  { id: 'n-ard', name_en: 'Ard Cinema', name_mn: 'Ард кино театр', lon: 106.8952, lat: 47.9165, centrality: 2, district: 'Bayangol' },
  { id: 'n-peace-w', name_en: 'Peace Ave West', name_mn: 'Энх тайвны өргөн чөлөө (баруун)', lon: 106.9042, lat: 47.9177, centrality: 2, district: 'Chingeltei' },
  { id: 'n-sukhbaatar', name_en: 'Sukhbaatar Square', name_mn: 'Сүхбаатарын талбай', lon: 106.9176, lat: 47.9188, centrality: 2, district: 'Chingeltei' },
  { id: 'n-peace-e', name_en: 'Peace Ave East', name_mn: 'Энх тайвны өргөн чөлөө (зүүн)', lon: 106.9352, lat: 47.9185, centrality: 2, district: 'Sukhbaatar' },
  { id: 'n-13r', name_en: '13th Khoroolol', name_mn: '13-р хороолол', lon: 106.9520, lat: 47.9178, centrality: 1, district: 'Bayanzurkh' },
  { id: 'n-sansar', name_en: 'Sansar', name_mn: 'Сансар', lon: 106.9662, lat: 47.9202, centrality: 1, district: 'Bayanzurkh' },
  { id: 'n-bayanzurkh', name_en: 'Bayanzurkh', name_mn: 'Баянзүрх', lon: 106.9855, lat: 47.9218, centrality: 1, district: 'Bayanzurkh' },
  { id: 'n-amgalan', name_en: 'Amgalan', name_mn: 'Амгалан', lon: 107.0090, lat: 47.9240, centrality: 0, district: 'Bayanzurkh' },

  // --- north-west: Bayankhoshuu corridor (S5 names this road)
  { id: 'n-bkh-1', name_en: 'Bayankhoshuu Rd (south)', name_mn: 'Баянхошуу зам (урд)', lon: 106.8460, lat: 47.9330, centrality: 1, district: 'Songino Khairkhan' },
  { id: 'n-bkh-2', name_en: 'Bayankhoshuu', name_mn: 'Баянхошуу', lon: 106.8385, lat: 47.9470, centrality: 0, district: 'Songino Khairkhan' },
  { id: 'n-bkh-3', name_en: 'Bayankhoshuu (north)', name_mn: 'Баянхошуу (хойд)', lon: 106.8310, lat: 47.9605, centrality: 0, district: 'Songino Khairkhan' },
  { id: 'n-denjiin', name_en: 'Denjiin Myanga', name_mn: 'Дэнжийн мянга', lon: 106.8790, lat: 47.9440, centrality: 0, district: 'Chingeltei' },

  // --- north
  { id: 'n-5khoroo', name_en: '5th Khoroo', name_mn: '5-р хороо', lon: 106.9060, lat: 47.9360, centrality: 1, district: 'Chingeltei' },
  { id: 'n-chingeltei', name_en: 'Chingeltei', name_mn: 'Чингэлтэй', lon: 106.9165, lat: 47.9455, centrality: 0, district: 'Chingeltei' },
  { id: 'n-selbe', name_en: 'Selbe', name_mn: 'Сэлбэ', lon: 106.9290, lat: 47.9390, centrality: 1, district: 'Sukhbaatar' },
  { id: 'n-dambadarjaa', name_en: 'Dambadarjaa', name_mn: 'Дамбадаржаа', lon: 106.9430, lat: 47.9640, centrality: 0, district: 'Sukhbaatar' },

  // --- Ikh Toiruu ring
  { id: 'n-toiruu-nw', name_en: 'Ikh Toiruu NW', name_mn: 'Их тойруу (баруун хойд)', lon: 106.8930, lat: 47.9300, centrality: 1, district: 'Chingeltei' },
  { id: 'n-toiruu-ne', name_en: 'Ikh Toiruu NE', name_mn: 'Их тойруу (зүүн хойд)', lon: 106.9440, lat: 47.9285, centrality: 1, district: 'Sukhbaatar' },
  { id: 'n-toiruu-se', name_en: 'Ikh Toiruu SE', name_mn: 'Их тойруу (зүүн урд)', lon: 106.9470, lat: 47.9065, centrality: 1, district: 'Bayanzurkh' },
  { id: 'n-toiruu-sw', name_en: 'Ikh Toiruu SW', name_mn: 'Их тойруу (баруун урд)', lon: 106.8880, lat: 47.9060, centrality: 1, district: 'Khan-Uul' },

  // --- south
  { id: 'n-officers', name_en: "Officers' Palace", name_mn: 'Офицеруудын ордон', lon: 106.9105, lat: 47.9085, centrality: 2, district: 'Khan-Uul' },
  { id: 'n-khanuul', name_en: 'Khan-Uul', name_mn: 'Хан-Уул', lon: 106.9010, lat: 47.8930, centrality: 1, district: 'Khan-Uul' },
  { id: 'n-zaisan', name_en: 'Zaisan', name_mn: 'Зайсан', lon: 106.9185, lat: 47.8760, centrality: 0, district: 'Khan-Uul' },
  { id: 'n-yarmag', name_en: 'Yarmag', name_mn: 'Ярмаг', lon: 106.8430, lat: 47.8760, centrality: 0, district: 'Khan-Uul' },
  { id: 'n-buyant', name_en: 'Buyant-Ukhaa', name_mn: 'Буянт-Ухаа', lon: 106.7960, lat: 47.8560, centrality: 0, district: 'Khan-Uul' },
  { id: 'n-nisekh', name_en: 'Nisekh', name_mn: 'Нисэх', lon: 106.8180, lat: 47.8650, centrality: 0, district: 'Khan-Uul' },

  // --- east / outer
  { id: 'n-tolgoit-e', name_en: 'Uliastai', name_mn: 'Улиастай', lon: 107.0290, lat: 47.9020, centrality: 0, district: 'Bayanzurkh' },
  { id: 'n-nalaikh', name_en: 'Nalaikh Rd', name_mn: 'Налайхын зам', lon: 107.0850, lat: 47.8830, centrality: 0, district: 'Nalaikh' },
  { id: 'n-shadivlan', name_en: 'Shadivlan', name_mn: 'Шадивлан', lon: 107.0520, lat: 47.9520, centrality: 0, district: 'Sukhbaatar' },

  // --- far west
  { id: 'n-songino', name_en: 'Songino', name_mn: 'Сонгино', lon: 106.7550, lat: 47.9080, centrality: 0, district: 'Songino Khairkhan' },
  { id: 'n-emeelt', name_en: 'Emeelt', name_mn: 'Эмээлт', lon: 106.7180, lat: 47.9000, centrality: 0, district: 'Songino Khairkhan' },
];

/** Undirected edges. Every pair listed here is a drivable corridor segment. */
export const EDGES: [string, string][] = [
  // Peace Avenue spine
  ['n-tolgoit', 'n-tsaiz'], ['n-tsaiz', 'n-dragon'], ['n-dragon', 'n-bayangol'],
  ['n-bayangol', 'n-3r4r'], ['n-3r4r', 'n-ard'], ['n-ard', 'n-peace-w'],
  ['n-peace-w', 'n-sukhbaatar'], ['n-sukhbaatar', 'n-peace-e'], ['n-peace-e', 'n-13r'],
  ['n-13r', 'n-sansar'], ['n-sansar', 'n-bayanzurkh'], ['n-bayanzurkh', 'n-amgalan'],
  // Bayankhoshuu corridor
  ['n-dragon', 'n-bkh-1'], ['n-bkh-1', 'n-bkh-2'], ['n-bkh-2', 'n-bkh-3'],
  ['n-bkh-1', 'n-denjiin'], ['n-denjiin', 'n-5khoroo'],
  // north
  ['n-peace-w', 'n-5khoroo'], ['n-5khoroo', 'n-chingeltei'], ['n-chingeltei', 'n-selbe'],
  ['n-selbe', 'n-dambadarjaa'], ['n-sukhbaatar', 'n-selbe'],
  // ring
  ['n-toiruu-nw', 'n-5khoroo'], ['n-toiruu-nw', 'n-ard'], ['n-toiruu-nw', 'n-toiruu-ne'],
  ['n-toiruu-ne', 'n-selbe'], ['n-toiruu-ne', 'n-13r'], ['n-toiruu-ne', 'n-toiruu-se'],
  ['n-toiruu-se', 'n-13r'], ['n-toiruu-se', 'n-officers'], ['n-toiruu-se', 'n-toiruu-sw'],
  ['n-toiruu-sw', 'n-officers'], ['n-toiruu-sw', 'n-3r4r'], ['n-toiruu-sw', 'n-khanuul'],
  // south
  ['n-sukhbaatar', 'n-officers'], ['n-officers', 'n-khanuul'], ['n-khanuul', 'n-zaisan'],
  ['n-khanuul', 'n-yarmag'], ['n-yarmag', 'n-nisekh'], ['n-nisekh', 'n-buyant'],
  ['n-yarmag', 'n-dragon'],
  // east / outer
  ['n-bayanzurkh', 'n-tolgoit-e'], ['n-tolgoit-e', 'n-nalaikh'], ['n-amgalan', 'n-shadivlan'],
  ['n-bayanzurkh', 'n-toiruu-se'],
  // far west
  ['n-tolgoit', 'n-songino'], ['n-songino', 'n-emeelt'], ['n-tsaiz', 'n-bkh-1'],
];

/** Nodes far enough out that a route touching one counts as suburban. */
export const OUTER = new Set([
  'n-emeelt', 'n-songino', 'n-nalaikh', 'n-shadivlan', 'n-buyant', 'n-nisekh',
  'n-zaisan', 'n-bkh-3', 'n-dambadarjaa', 'n-tolgoit-e', 'n-amgalan',
]);

export const NODE_BY_ID = new Map(NODES.map((n) => [n.id, n]));

export const ADJ: Map<string, string[]> = (() => {
  const m = new Map<string, string[]>();
  for (const n of NODES) m.set(n.id, []);
  for (const [a, b] of EDGES) {
    m.get(a)!.push(b);
    m.get(b)!.push(a);
  }
  return m;
})();

export const UB_BBOX: [number, number, number, number] = [106.70, 47.84, 107.10, 47.98];
export const UB_CENTER: [number, number] = [106.9176, 47.9188];
